version: '3.8'
services:
   db:
     image: mysql:latest
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: db01
     ports:
       - 3306:3306
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat:9
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db01
volumes:
    db_vol:      